spring.application.name=api-gateway
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/meet-me-at}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/meet-me-at/protocol/openid-connect/certs}
meet-me-at.security.jwt.required-audience=${KEYCLOAK_AUDIENCE:meet-me-at-api}